# @file remove_cruft.sh - Written by Joe Turner
#
# Copyright Agave Mountain, Inc. 2013; All Rights Reserved                                                
#---------------------------------------------------------------------

echo "formatting code."
astyle --recursive "*.cpp"
astyle --recursive "*.hpp"
astyle --recursive "*.h"

# remove backup files generated by some editors


# remove all astyle backup copies (cruft).
echo "removing .orig files.."
rm `find . -name "*.orig" | xargs`

# remove doxygen generated documentation.
echo "removing doxygen documentation."
rm -rf html

dos2unix src/*.cpp
dos2unix include/*.hpp
dos2unix uniitest/*.cpp

